//! Generates the list of checks from the files in `src/checks/`, so adding a
//! check is just adding a file there.
//!
//! Every `.rs` file in that directory is a check. It must export
//! `pub const CHECK: Kind`, either a source check or a branch check, and its
//! `name()` must equal the file name without `.rs`, which a generated test
//! enforces. The output is included by
//! `main.rs` as the `checks` module.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let checks_dir = Path::new(&manifest_dir).join("src").join("checks");
    let out_path = Path::new(&env::var("OUT_DIR").unwrap()).join("checks.rs");

    // Rebuild when a file in src/checks is added, removed or edited.
    println!("cargo:rerun-if-changed={}", checks_dir.display());

    let mut names: Vec<String> = fs::read_dir(&checks_dir)
        .expect("src/checks must exist")
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .map(|path| path.file_stem().unwrap().to_str().unwrap().to_string())
        .collect();
    names.sort();

    let mut out =
        String::from("// Generated by build.rs from the files in src/checks/. Do not edit.\n\n");

    for name in &names {
        let file = checks_dir.join(format!("{name}.rs"));
        out += &format!(
            "#[path = {:?}]\npub mod {name};\n",
            file.display().to_string()
        );
    }

    out += "\n/// Every check, in file name order.\n";
    out += "pub fn all() -> Vec<crate::check::Kind> {\n    vec![\n";
    for name in &names {
        out += &format!("        {name}::CHECK,\n");
    }
    out += "    ]\n}\n";

    out += "\n#[cfg(test)]\nmod generated_tests {\n";
    out += "    /// `--disable` and the findings refer to checks by file name.\n";
    out += "    #[test]\n    fn check_names_match_file_names() {\n";
    for name in &names {
        out += &format!("        assert_eq!(super::{name}::CHECK.name(), {name:?});\n");
    }
    out += "    }\n}\n";

    fs::write(&out_path, out).unwrap();
}
