//! Runs every check in `checks::all()` over the given paths (default `lib`).
//!
//! Fast pass first, printing findings as each file finishes. Then the slow
//! pass over every file a check flagged as potential. Exits `1` when any
//! finding is confirmed and `2` when the arguments are wrong.
//!
//! Options, each repeatable:
//!
//! - `--ignore NAME` skips directories called `NAME` wherever they appear.
//! - `--disable NAME` skips the check called `NAME`.
//!
//! `mix app.checks` fills these in from `.app_checks.exs`.

mod check;

mod checks {
    //! The list of checks. Generated by `build.rs` from the files in
    //! `src/checks/`, so there is nothing to edit here when adding one.
    include!(concat!(env!("OUT_DIR"), "/checks.rs"));
}

use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use rayon::prelude::*;
use walkdir::WalkDir;

use check::{Check, Confidence, Finding, SourceFile};

const EXTENSIONS: &[&str] = &["ex", "exs", "heex"];

#[derive(Debug, Default)]
struct Options {
    roots: Vec<PathBuf>,
    ignored_dirs: Vec<String>,
    disabled: Vec<String>,
}

/// A (check, file) pair the fast pass could not settle.
struct Flagged {
    check: usize,
    file: usize,
    /// Confirmed by the fast pass and already printed, so the slow pass
    /// does not print them again.
    reported: Vec<Finding>,
}

fn main() -> ExitCode {
    let options = match parse_args(std::env::args().skip(1)) {
        Ok(options) => options,
        Err(message) => {
            eprintln!("{message}");
            return ExitCode::from(2);
        }
    };

    let checks = match select_checks(checks::all(), &options.disabled) {
        Ok(checks) => checks,
        Err(message) => {
            eprintln!("{message}");
            return ExitCode::from(2);
        }
    };

    let files = collect_files(&options.roots, &options.ignored_dirs);

    // Fast pass: every check on every file, in parallel, printing per file.
    let (fast_confirmed, flagged) = files
        .par_iter()
        .enumerate()
        .map(|(file_index, file)| {
            let mut confirmed = 0;
            let mut flagged = Vec::new();
            let mut out = io::stdout().lock();

            for (check_index, check) in checks.iter().enumerate() {
                let mut findings = check.fast(file);
                confirmed += report(&mut out, file, *check, &mut findings);

                if findings
                    .iter()
                    .any(|f| f.confidence == Confidence::Potential)
                {
                    findings.retain(|f| f.confidence == Confidence::Confirmed);
                    flagged.push(Flagged {
                        check: check_index,
                        file: file_index,
                        reported: findings,
                    });
                }
            }

            (confirmed, flagged)
        })
        .reduce(
            || (0, Vec::new()),
            |(a, mut flagged), (b, more)| {
                flagged.extend(more);
                (a + b, flagged)
            },
        );

    // Slow pass: only the flagged pairs, in parallel.
    let slow_confirmed: usize = flagged
        .par_iter()
        .map(|flag| {
            let (check, file) = (checks[flag.check], &files[flag.file]);
            let mut findings = check.slow(file);
            debug_assert!(
                findings
                    .iter()
                    .all(|f| f.confidence == Confidence::Confirmed)
            );
            findings.retain(|f| !flag.reported.contains(f));
            report(&mut io::stdout().lock(), file, check, &mut findings)
        })
        .sum();

    let total = fast_confirmed + slow_confirmed;
    let disabled = match options.disabled.len() {
        0 => String::new(),
        n => format!(", {n} disabled"),
    };
    println!(
        "{} check(s) over {} file(s), {} slow pass(es), {} confirmed finding(s){disabled}",
        checks.len(),
        files.len(),
        flagged.len(),
        total
    );

    if total == 0 {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}

fn parse_args(args: impl Iterator<Item = String>) -> Result<Options, String> {
    let mut args = args.peekable();
    let mut options = Options::default();

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--ignore" => options.ignored_dirs.push(value_for(&mut args, &arg)?),
            "--disable" => options.disabled.push(value_for(&mut args, &arg)?),
            flag if flag.starts_with("--") => {
                return Err(format!(
                    "unknown option {flag}; the options are --ignore NAME and --disable NAME"
                ));
            }
            path => options.roots.push(PathBuf::from(path)),
        }
    }

    if options.roots.is_empty() {
        options.roots.push(PathBuf::from("lib"));
    }

    Ok(options)
}

fn value_for(args: &mut impl Iterator<Item = String>, flag: &str) -> Result<String, String> {
    args.next()
        .ok_or_else(|| format!("{flag} needs a name after it"))
}

/// Every check except the disabled ones. A disabled name that matches no
/// check is an error, so a typo cannot quietly disable nothing.
fn select_checks<'a>(
    all: Vec<&'a dyn Check>,
    disabled: &[String],
) -> Result<Vec<&'a dyn Check>, String> {
    for name in disabled {
        if !all.iter().any(|check| check.name() == name) {
            let names: Vec<&str> = all.iter().map(|check| check.name()).collect();
            return Err(format!(
                "cannot disable {name}, there is no such check; the checks are: {}",
                names.join(", ")
            ));
        }
    }

    Ok(all
        .into_iter()
        .filter(|check| !disabled.iter().any(|name| name == check.name()))
        .collect())
}

/// Prints `findings` in line order and returns how many were confirmed.
fn report(
    out: &mut impl Write,
    file: &SourceFile,
    check: &dyn Check,
    findings: &mut [Finding],
) -> usize {
    findings.sort_by_key(|f| f.line);

    let mut confirmed = 0;
    for finding in findings.iter() {
        let label = match finding.confidence {
            Confidence::Confirmed => {
                confirmed += 1;
                "confirmed"
            }
            Confidence::Potential => "potential",
        };
        let _ = writeln!(
            out,
            "{}:{}: {} [{}, {label}]",
            file.path.display(),
            finding.line,
            finding.message,
            check.name()
        );
    }
    confirmed
}

/// Every readable UTF-8 source file under `roots` with a recognised extension,
/// skipping directories named in `ignored_dirs` unless named as a root.
fn collect_files(roots: &[PathBuf], ignored_dirs: &[String]) -> Vec<SourceFile> {
    roots
        .iter()
        .flat_map(|root| {
            WalkDir::new(root)
                .into_iter()
                .filter_entry(|entry| {
                    entry.depth() == 0 || !is_ignored_dir(entry.path(), ignored_dirs)
                })
                .filter_map(Result::ok)
        })
        .filter(|entry| entry.file_type().is_file() && has_source_extension(entry.path()))
        .filter_map(|entry| {
            let path = entry.into_path();
            match std::fs::read_to_string(&path) {
                Ok(contents) => Some(SourceFile { path, contents }),
                Err(error) => {
                    eprintln!("skipping {}: {error}", path.display());
                    None
                }
            }
        })
        .collect()
}

fn is_ignored_dir(path: &Path, ignored_dirs: &[String]) -> bool {
    path.is_dir()
        && path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| ignored_dirs.iter().any(|ignored| ignored == name))
}

fn has_source_extension(path: &Path) -> bool {
    path.extension()
        .and_then(|ext| ext.to_str())
        .is_some_and(|ext| EXTENSIONS.contains(&ext))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(args: &[&str]) -> Result<Options, String> {
        parse_args(args.iter().map(|s| s.to_string()))
    }

    #[test]
    fn defaults_to_lib_with_nothing_ignored_or_disabled() {
        let options = parse(&[]).unwrap();
        assert_eq!(options.roots, vec![PathBuf::from("lib")]);
        assert!(options.ignored_dirs.is_empty());
        assert!(options.disabled.is_empty());
    }

    #[test]
    fn collects_repeated_options_and_paths() {
        let options = parse(&[
            "--ignore",
            "deps",
            "lib",
            "--disable",
            "a",
            "--ignore",
            "_build",
            "test",
        ])
        .unwrap();
        assert_eq!(
            options.roots,
            vec![PathBuf::from("lib"), PathBuf::from("test")]
        );
        assert_eq!(options.ignored_dirs, vec!["deps", "_build"]);
        assert_eq!(options.disabled, vec!["a"]);
    }

    #[test]
    fn rejects_unknown_options_and_missing_values() {
        assert!(
            parse(&["--nope"])
                .unwrap_err()
                .contains("unknown option --nope")
        );
        assert!(parse(&["--disable"]).unwrap_err().contains("needs a name"));
    }

    #[test]
    fn disabling_an_unknown_check_is_an_error() {
        let error = select_checks(checks::all(), &["nope".to_string()])
            .err()
            .unwrap();
        assert!(error.contains("no such check"));
        assert!(error.contains("raw_html_tags"));
    }

    #[test]
    fn disabling_a_check_removes_it() {
        let selected = select_checks(checks::all(), &["raw_html_tags".to_string()]).unwrap();
        assert!(selected.iter().all(|check| check.name() != "raw_html_tags"));
    }
}
